# Generated by Django 6.0.2 on 2026-02-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_voting_enabled',
            field=models.BooleanField(default=True, help_text='Manual override to enable/disable voting'),
        ),
    ]
