# Generated by Django 6.0.2 on 2026-02-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_core', '0002_election_is_voting_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='signature',
            field=models.TextField(blank=True, help_text='HMAC-SHA256 signature of the vote data', null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='verification_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
