# Generated by Django 6.0.2 on 2026-02-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_core', '0003_vote_signature_vote_verification_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_email_enabled', models.BooleanField(default=True, help_text='Global switch for all system emails')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.AddField(
            model_name='election',
            name='send_receipts',
            field=models.BooleanField(default=True, help_text='Send digital receipts after voting'),
        ),
    ]
