# Generated by Django 6.0.2 on 2026-02-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_core', '0004_systemconfig_election_send_receipts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='is_email_enabled',
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_otp_emails',
            field=models.BooleanField(default=True, help_text='Global switch for OTP verification emails'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_receipt_emails',
            field=models.BooleanField(default=True, help_text='Global switch for voting receipt emails'),
        ),
    ]
