# Generated by Django 6.0.2 on 2026-02-18 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_core', '0005_remove_systemconfig_is_email_enabled_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together={('election', 'matric_number')},
        ),
        migrations.AlterField(
            model_name='voter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together={('election', 'matric_number'), ('user', 'election')},
        ),
    ]
