# Generated by Django 6.0.2 on 2026-02-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_core', '0006_alter_voter_unique_together_alter_voter_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='verification_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
