# Generated by Django 6.0.2 on 2026-02-18 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_core', '0007_alter_vote_verification_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], max_length=20, unique=True)),
                ('price_per_email', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_emails', models.IntegerField(default=50, help_text='0 = unlimited')),
            ],
            options={
                'verbose_name': 'Plan Pricing',
                'verbose_name_plural': 'Plan Pricing',
            },
        ),
        migrations.AddField(
            model_name='election',
            name='custom_slug',
            field=models.SlugField(blank=True, help_text='Custom URL slug for Premium plan', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='election',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='FREE', max_length=20),
        ),
        migrations.CreateModel(
            name='ElectionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], max_length=20)),
                ('email_count', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paystack_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='election_core.election')),
            ],
        ),
    ]
