# Generated by Django 6.0.2 on 2026-02-18 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_core', '0008_planpricing_election_custom_slug_election_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionpayment',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='election_core.election'),
        ),
    ]
