# Generated by Django 6.0.2 on 2026-02-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_core', '0009_alter_electionpayment_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload logo (Standard/Premium)', null=True, upload_to='election_logos/'),
        ),
        migrations.AddField(
            model_name='election',
            name='short_id',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='election',
            name='theme',
            field=models.CharField(default='default', help_text='UI Theme for Premium plan', max_length=50),
        ),
    ]
