# Generated by Django 6.0.2 on 2026-02-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_core', '0010_election_logo_election_short_id_election_theme'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['election', 'candidate'], name='vote_election_candidate_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['election', 'position'], name='vote_election_position_idx'),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['user', 'election'], name='voter_user_election_idx'),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['election', 'has_voted'], name='voter_election_voted_idx'),
        ),
    ]
