# Generated by Django 6.0.3 on 2026-03-21 23:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_core', '0012_election_is_sealed_election_result_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='accreditation_type',
            field=models.CharField(choices=[('OTP', 'Email OTP'), ('TOKEN', 'Token-based')], default='OTP', max_length=10),
        ),
        migrations.AddField(
            model_name='election',
            name='is_cleared',
            field=models.BooleanField(default=False, help_text='Superadmin clearance to go live'),
        ),
        migrations.AddField(
            model_name='election',
            name='last_token_send_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='is_token_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ElectionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('allowed_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='election_core.allowedemail')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='election_core.election')),
            ],
        ),
    ]
