# Generated by Django 6.0.3 on 2026-03-23 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "election_core",
            "0013_election_accreditation_type_election_is_cleared_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="contest_image",
            field=models.ImageField(
                blank=True,
                help_text="General image for Contestant Election",
                null=True,
                upload_to="contests/",
            ),
        ),
        migrations.AddField(
            model_name="election",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description for Contestant Election", null=True
            ),
        ),
        migrations.AddField(
            model_name="election",
            name="election_type",
            field=models.CharField(
                choices=[
                    ("POLITICAL", "Political Election"),
                    ("CONTESTANT", "Contestant Election"),
                ],
                default="POLITICAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="election",
            name="voting_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount organizer gets per vote (Contestant only)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="contest_charge_config",
            field=models.JSONField(
                default=list, help_text="Dynamic surcharge ranges for contestant votes"
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="vote",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vote",
            name="paystack_reference",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="voter_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="voter_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "charge_amount",
                    models.DecimalField(decimal_places=2, default=500, max_digits=10),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=20)),
                ("bank_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="election_core.wallet",
                    ),
                ),
            ],
        ),
    ]
