# Generated by Django 6.0.3 on 2026-03-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election_core", "0014_election_contest_image_election_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="instagram",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="tiktok",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="twitter",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="faculty",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
