# Generated by Django 6.0.3 on 2026-03-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election_core", "0015_candidate_instagram_candidate_tiktok_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
