# Generated by Django 6.0.2 on 2026-03-24 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election_core", "0016_vote_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="electiontoken",
            name="last_resend_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="electiontoken",
            name="resend_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="election",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="election_core.institution",
            ),
        ),
    ]
